<!-- SENG2050 Assignment 3 - Semester 1 2019
     c3237487_c3215435_c3293398_FinalProject

     This is the 'home' or 'main' page of the website, from which users can view notifications,
     issues, the knowledge base, and for reporters to submit new issues

     Much of the contents of this page is generated by other jsps to break down the page
     into more manageable, independent subsections
 -->


<jsp:useBean id="issueManager" class="classPackage.IssueManager" scope="session" />
<jsp:useBean id="user" class="classPackage.User" scope="session" />
<jsp:useBean id="currSession" class="classPackage.SessionTracker" scope="session"/>
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <link rel="stylesheet" type="text/css" href="Style.css" /> 
        <title>Dashboard</title>
    </head>
    <body>
        <div class="SiteHeader">
            <div class="NavBar">
                <div class="LogoBlock">
                    <img class="logo" src="images/BasicHelpDeskLogo.png" alt="BasicHelpDesk" />
                </div>
                <button class="autowidth" onclick="location.href='#NotifLink'" name="navButton" value="notifications">Notifications</button>
                <button class="autowidth" onclick="location.href='#IssueLink'" name="navButton" value="viewIssues">View Issues</button>
                <button class="autowidth" onclick="location.href='#KnowLink'" name="navButton" value="knowledgeBase">Knowledge Base</button>
                <form class="inlineForm" id="headerButtons" method="post" onsubmit="classes/WebDispatch">
                    <button class="autowidth" onclick="submit" name="logErrorButton" value="Log Out">Log out</button>
                </form>
            </div>
        </div>
        <div class="NoPadding" id="PageContent">

        <!-- Loading all issues into the issue manager bean for the included jsps to read form -->
        <%issueManager.loadAllIssues();%>
        
        <!-- This section will display a confirmation dialog if a user submits a new issue -->
		<% if ( currSession.getState() == classPackage.SessionTracker.State.NEWISSUEDASHBOARD) { %>
			<% if ( currSession.getDoOnce() == false) { %>
					<script>
						alert("New issue successfully submitted. Thankyou");
					</script>
					<% currSession.setDoOnce(true); %>
			<%}%>
        <%}%>

        <div class="IncludeNotificationsIndex" id="NotifLink">
            <%@ include file="NotificationIndex.jsp" %>
        </div>          
        <div class="IncludeUserIssueIndex" id="IssueLink">
            <%@include file="UserIssueIndex.jsp" %>
        </div>
        <div class="IncludeKnowledgeBase" id="KnowLink">
            <%@include file="KnowledgeBase.jsp" %>
        </div>

        <!-- If the user is a reporter, display the Submit New Issue block -->
        <% if (!user.getUserType()) { %>
            <div>
                <div class="NewIssueBlock">
                    <b>Can't find a solution?</b>
                    <form name="newIssueButton" method="post" onsubmit="classes/WebDispatch">
                        <button onclick="submit" name="submitNewIssue" value="SubmitNewIssue">
                            Submit New Issue
                        </button>
                    </form>	
                </div>
            </div>
            <!-- This div resolves an issue with the floated section sitting below the centred whitespace -->
            <div class="increaseBodyLength"><p>a</p><p>a</p> </div>
        <% } %>

        </div>
    </body>
</html>
